Sam and JSON conversion B-type tag support and bug fixes
pezmaster31/bamtools pull request #171
Opened 2017-11-07 15:33 UTC by daviesrob

This makes `bamtools convert` able to correctly output (in SAM format) `auxf#values.bam` (derived from [auxf#values.sam](https://github.com/samtools/htslib/blob/e2ea37705775e80d5987c5aaf8718f95b0875492/test/auxf%23values.sam)) in the attached zip file:

[testbams.zip](https://github.com/pezmaster31/bamtools/files/1450527/testbams.zip)

It adds support for B array tags, and fixes a casting bug which caused `C` (unsigned byte) tags to be written incorrectly on platforms where `char` is signed.  x86 and x86-64 both have signed char by default.

It also fixes buffer overrun bugs in the tag printing code that could be triggered by broken BAM files (see `broken1.bam` in the zip file), and adds checks to catch invalid tag types (`broken2.bam` and `broken3.bam`).

2021-05-24 13:26 UTC, SoapZA commented
could you rebase your branch (don't forget to reformat as well)?

2021-05-25 10:28 UTC, daviesrob commented
I've pushed a squashed and rebased version for you.  Let me know if you need anything else.

2021-05-25 12:01 UTC, SoapGentoo commented on src/toolkit/bamtools_convert.cpp
> +                throw BadDataException("Unknown B array type");
```suggestion
                throw BadDataException(std::string("Unknown B array type: ") + tagData[0]);
```
maybe? will definitely help with debugging

2021-05-25 12:03 UTC, SoapGentoo commented on src/toolkit/bamtools_convert.cpp
> +                m_out << static_cast<int16_t>(tagData[index]);
```suggestion
                m_out << int(static_cast<int8_t>(tagData[index]));;
```
consistency with line 601

2021-05-25 12:06 UTC, SoapGentoo commented on src/toolkit/bamtools_convert.cpp
> +                    m_out << "[";
```suggestion
                    m_out << '[';
```
Avoid string literals

2021-05-25 12:06 UTC, SoapGentoo commented on src/toolkit/bamtools_convert.cpp
> +                    m_out << "]";
```suggestion
                    m_out << ']';
```
Avoid string literals

2021-05-25 13:20 UTC, daviesrob commented
Updated.  Hopefully I got everything.

2021-05-25 13:26 UTC, SoapZA requested changes
two small niggles remaining

2021-05-25 13:26 UTC, SoapZA commented on src/toolkit/bamtools_convert.cpp
> +class BadDataException : public std::exception
missing `#include <exception>`

2021-05-25 13:26 UTC, SoapZA commented on src/toolkit/bamtools_convert.cpp
> +                throw BadDataException(std::string("Unknown B array type: " + tagData[0]));
```suggestion
                throw BadDataException(std::string("Unknown B array type: ") + tagData[0]);
```
this is wrong, you're doing pointer arithmetic on the string literal offset

2021-05-29 16:55 UTC, SoapZA approved these changes

2021-05-30 07:57 UTC, closed without merging